### PR TITLE
include tinyobjloader, fix missing `}`

### PR DESCRIPTION
**Pull request by FederAndInk**
Hi, Nihili0 from reddit here,

Here is your problem

### CODE REVIEW

**Comment by Snowapril** [comment]
oh my god, how kind you are. I'll check it out.

**Comment by Snowapril** [comment]
I reviewed and LGTM! I cannot understand why I don't realize that missing close embrace and why the compiler doesn't warn me.. Anyway, thanks for your contribution! This PR will be merged with the branch.

**Comment by FederAndInk** [comment]
Well as it is in a header the compiler was completely lost, I also had some weird errors:

```
error: use of undeclared identifier 'highp'; did you mean '::glm::highp'?
```

Finally, I found the issue by chance, when looking at headers. (it was ccls who found the issue, it was analyzing the headers separately, I like to have for each header a cpp file that includes it on top of it to have all headers compiled in isolation)

And it all compiled on Linux, great work btw.

**Comment by Snowapril** [comment]
Thanks 😊 This branch is on WIP to remove glm dependency. glm dependency in CMake and submodules was deleted, but  detaching dependency in source codes is still progressing.
